import {chromium} from 'playwright-core';import fs from 'node:fs/promises';import http from 'node:http';import path from 'node:path';
const root=path.resolve('preview-build');const target='public/screens';await fs.mkdir(target,{recursive:true});
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');const p=path.join(root,url.pathname==='/'?'index.html':decodeURIComponent(url.pathname));const b=await fs.readFile(p);res.setHeader('content-type',p.endsWith('.js')?'application/javascript':p.endsWith('.css')?'text/css':p.endsWith('.html')?'text/html':'application/octet-stream');res.end(b)}catch{res.statusCode=404;res.end()}});await new Promise(r=>server.listen(5199,'127.0.0.1',r));
const browser=await chromium.launch({executablePath:'/tmp/orbit-browser/chrome-headless-shell-linux64/chrome-headless-shell',args:['--no-sandbox']});const errors=[];const records=[];
for(const university of ['tnmgr','kuhs']){
 const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:3,reducedMotion:'reduce'});await context.route('**/*',r=>r.request().url().startsWith('http://127.0.0.1:5199')?r.continue():r.abort());
 await context.addInitScript(u=>{localStorage.setItem('orbit:attendance-v1',JSON.stringify([{id:'a1',name:'Pathology',kind:'theory',target:75,held:64,attended:55},{id:'a2',name:'Pharmacology',kind:'theory',target:75,held:61,attended:46},{id:'a3',name:'Microbiology',kind:'theory',target:75,held:58,attended:41}]));localStorage.setItem('orbit-profile-v1',JSON.stringify({display_name:'Sabari',year:'final',university:u}));},university);
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 const shots=[['questions','screen=browse&year=second-year&node=pathology,paper-1,cell-injury&title=Cell%20Injury'],['answer','screen=notesdemo&repetition=generated'],['personal-edit','screen=usernotesdemo&mode=edit'],['second','screen=browse&year=second-year'],['third','screen=browse&year=third-year']];
 for(const [name,q] of shots){await page.goto('http://127.0.0.1:5199/?'+q);await page.waitForTimeout(1500);await page.evaluate(()=>document.fonts.ready);if((await page.locator('body').innerText()).includes('Topic not found')){console.log('Rejected invalid topic capture',university,name);continue;}await page.screenshot({path:`${target}/${university}-${name}.png`});records.push({university,name,query:q,text:(await page.locator('body').innerText()).slice(0,2000)});await fs.writeFile(target+'/capture-more-records.json',JSON.stringify({records,errors},null,2));console.log('captured',university,name);}
 await page.goto('http://127.0.0.1:5199/?screen=browse&year=final-year');await page.waitForTimeout(1200);await page.locator('input').first().fill('skin');await page.waitForTimeout(500);await page.screenshot({path:`${target}/${university}-search.png`});await page.goto('http://127.0.0.1:5199/?screen=ankidemo');await page.waitForTimeout(700);await page.getByText('Show answer',{exact:true}).click({force:true});await page.waitForTimeout(300);await page.screenshot({path:`${target}/${university}-anki-answer.png`});
 await page.goto('http://127.0.0.1:5199/?screen=progress');await page.waitForTimeout(1200);await page.getByLabel('Attendance',{exact:true}).click({force:true});await page.waitForTimeout(400);await page.screenshot({path:`${target}/${university}-attendance.png`});
 await page.goto('http://127.0.0.1:5199/?screen=home');await page.waitForTimeout(1000);await page.getByLabel('Settings',{exact:true}).click({force:true});await page.waitForTimeout(350);await page.screenshot({path:`${target}/${university}-settings.png`});await context.close();
}
await fs.writeFile(target+'/capture-more-records.json',JSON.stringify({records,errors},null,2));await browser.close();server.close();console.log('errors',errors);
