import React from 'react';import {AbsoluteFill,Audio,Img,Sequence,staticFile,useCurrentFrame,useVideoConfig,interpolate,Easing,spring} from 'remotion';import shots from '../storyboard.json';import musicShots from '../storyboard-music.json';import fastShots from '../storyboard-fast.json';import beatShots from '../storyboard-beat.json';import {Mascot} from './Mascot';
const ez=Easing.bezier(.2,.86,.24,1);const opts={extrapolateLeft:'clamp' as const,extrapolateRight:'clamp' as const,easing:ez};const v=(t:number,x:number[],y:number[])=>interpolate(t,x,y,opts);
type Pose=[number,number,number,number,number];
function Phone({file,pose=[0,0,1,0,0],opacity=1,crop=false}:{file:string,pose?:Pose,opacity?:number,crop?:boolean}){const [x,y,scale,r,ry]=pose;return <div style={{position:'absolute',left:0,right:0,top:110,height:1090,overflow:'hidden'}}><div style={{position:'absolute',left:300,top:20,width:480,height:1040,boxSizing:'border-box',opacity,padding:6,borderRadius:34,background:'linear-gradient(135deg,#8b93a4,#111a2b 24%,#242d3c 78%,#8899b1)',transform:`translate(${x}px,${y}px) scale(${scale}) rotate(${r}deg) rotateY(${ry}deg)`,boxShadow:'0 20px 50px #0007',overflow:'hidden'}}><div style={{width:'100%',height:'100%',borderRadius:28,overflow:'hidden',position:'relative',background:'#05070b'}}><Img src={staticFile(`screens/${file}.png`)} style={{width:'100%',height:'100%',position:'absolute',top:0,objectFit:'contain'}}/></div></div></div>}

function Words({text,t,big=false}:{text:string,t:number,big?:boolean}){return <>{text.split('\n').map((l,i)=><div key={i} style={{opacity:v(t,[.04+i*.08,.38+i*.08],[0,1]),transform:`translateY(${v(t,[.04+i*.08,.38+i*.08],[big?22:14,0])}px)`}}>{l}</div>)}</>}

function Caption({s,t}:{s:any,t:number}){return <div style={{position:'absolute',left:75,right:75,top:1260,textAlign:'center',opacity:v(t,[0,.2,s.d-.24,s.d],[0,1,1,0])}}><div style={{fontSize:59,fontWeight:780,letterSpacing:-1.9,lineHeight:1.08}}><Words text={s.caption} t={t}/></div>{s.sub&&<div style={{fontSize:29,color:'#b6c0d3',lineHeight:1.3,marginTop:20}}>{s.sub}</div>}<div style={{width:v(t,[.25,.8],[0,155]),height:4,borderRadius:4,background:s.accent||'#65ded7',margin:'24px auto 0'}}/></div>}
function Play(){return <div style={{display:'inline-flex',alignItems:'center',gap:24,padding:'18px 30px',border:'2px solid #8f99ac',background:'#05080d',borderRadius:18}}><Img src={staticFile('google-play-logo.svg')} style={{width:65,height:73}}/><div style={{textAlign:'left'}}><div style={{fontSize:20,letterSpacing:1}}>GET IT ON</div><div style={{fontSize:43,fontWeight:500}}>Google Play</div></div></div>}
function Scene({s,index,music=false,fast=false}:{s:any,index:number,music?:boolean,fast?:boolean}){const f=useCurrentFrame();const t=f/60;const accent=s.accent||'#65ded7';const ent=spring({frame:f,fps:60,config:{damping:19,stiffness:140,mass:1}});const exit=v(t,[s.d-.27,s.d],[0,1]);const isLight=s.kind==='numbers';const alpha=1;const reveal=index===0?1:v(t,[0,.25],[0,1]);const feature=['screen','home','mcq','cards','dual','ai','universities','montageHook'].includes(s.kind);const fly=0;const state=s.kind==='ai'?'thinking':s.kind==='end'||s.kind==='numbers'?'wink':'wide';
 const entrance=fast?.22:music?.48:.65;
 let p:Pose=[v(t,[0,entrance],[index%2?260:-260,0]),v(t,[0,entrance,s.d-.25],[24,0,-3]),v(t,[0,entrance,s.d-.25],[.84,.94,.96]),v(t,[0,entrance,s.d-.25],[index%2?-5:5,0,index%2?.6:-.6]),0];
 if(s.mode==='pull')p=[0,v(t,[0,.7],[25,0]),v(t,[0,.7,s.d-.25],[.89,.94,.96]),v(t,[0,.7],[3,0]),0];
 if(s.kind==='cards'){const mid=(s.slot||3.35)/2;p[4]=v(t,[mid-.18,mid,mid+.18],[0,88,0]);}

 return <AbsoluteFill style={{background:isLight?'#eef7f4':'#070b14',color:isLight?'#101c2c':'#f4f7ff',opacity:alpha,clipPath:`inset(0 ${100*(1-reveal)}% 0 0)`,filter:fast?`blur(${v(t,[0,.12],[3,0])}px)`:undefined,overflow:'hidden',perspective:1800}}>
 <div style={{position:'absolute',inset:0,background:isLight?'radial-gradient(circle at 70% 35%,#bedce766,transparent 60%)':`radial-gradient(ellipse at ${35+index%3*15}% 38%,${accent}12,transparent 64%)`}}/>
 <div style={{position:'absolute',left:-240,top:300,width:1580,height:900,borderRadius:'50%',border:`1px solid ${isLight?'#a4c5cd66':accent+'17'}`,transform:`rotate(${-28+index*5+t*2}deg)`}}/>
 {feature&&<><div style={{position:'absolute',left:115,top:340,width:850,height:850,borderRadius:'50%',border:`2px solid ${accent}29`,transform:`scale(${v(t,[0,.7,s.d],[.7,1,1.04])}) rotate(${t*7}deg)`}}/><div style={{position:'absolute',left:145,top:720,width:790,height:2,background:`linear-gradient(90deg,transparent,${accent}66,transparent)`,opacity:v(t,[0,.4,.8],[0,1,0]),transform:`translateY(${v(t,[0,.8],[180,-180])}px)`}}/></>}
 {s.kind==='hook'&&<><div style={{position:'absolute',top:285,left:65,right:65,textAlign:'center',fontSize:110,fontWeight:800,lineHeight:1.02,letterSpacing:-5}}><Words text={s.caption} t={t} big/></div><div style={{position:'absolute',left:290,top:640,transform:`translateY(${(1-ent)*120}px) rotate(${v(t,[0,.8,s.d],[12,-4,2])}deg) scale(${.82+ent*.18})`}}><Mascot size={500} state="wide"/></div><div style={{position:'absolute',top:1280,left:80,right:80,textAlign:'center',fontSize:35,color:'#b3c0d4',opacity:v(t,[.55,1],[0,1])}}>Meet ORBIT MBBS.</div><div style={{position:'absolute',top:1400,left:130,right:130,textAlign:'center',fontSize:24,letterSpacing:3,color:accent}}>STUDY · RECALL · KEEP GOING</div></>}

 {s.kind==='montageHook'&&<>{['tnmgr-home','kuhs-subjects','tnmgr-questions'].map((file,i)=><Phone key={file} file={file} pose={[(i-1)*310+v(t,[0,.45],[i%2?750:-750,0]),15,.55+v(t,[.45,s.d-.25],[0,.015]),(i-1)*2,0]}/>)}</>}
 {s.kind==='universities'&&<>{s.files.map((file:string,i:number)=>{const swap=v(t,fast?[.74,.95]:[(s.slot||3.35)/2-.16,(s.slot||3.35)/2+.16],[0,1]);const opacity=i?swap:1-swap;const x=i?(1-swap)*800:-swap*800;return <Phone key={file} file={file} opacity={opacity} pose={[v(t,[0,fast?.22:.48],[650,0])+x,0,v(t,[0,.55,s.d-.25],[.85,.94,.96]),v(t,[0,.6],[-3,0]),0]}/>})}</>}
 {s.kind==='dual'&&<>{s.files.map((file:string,i:number)=><Phone key={file} file={file} pose={[v(t,[0,.65],[i?-900:900,i?245:-245]),0,.77+v(t,[.6,s.d-.25],[0,.01]),i?1:-1,0]}/>)}<div style={{position:'absolute',top:1230,left:110,width:350,textAlign:'center',fontSize:25,color:accent}}>{s.kind==='universities'?'TNMGR':'My Progress'}</div><div style={{position:'absolute',top:1230,right:110,width:350,textAlign:'center',fontSize:25,color:accent}}>{s.kind==='universities'?'KUHS':'Attendance'}</div>{index===1&&<div style={{position:'absolute',top:1390,left:70,right:70,textAlign:'center',fontSize:23,lineHeight:1.4,color:'#a9b9d1'}}>Tamil Nadu Dr. M.G.R. Medical University<br/>Kerala University of Health Sciences</div>}</>}
 {['screen','home','cards','mcq'].includes(s.kind)&&<Phone file={s.files?s.files[t>(s.kind==='cards'?(fast?.8:(s.slot||3.35)/2):(fast?.8:(s.slot||3.35)/2))?1:0]:s.file} pose={p}/>}
 {s.kind==='ai'&&<><Phone file={s.file} pose={[140+v(t,[0,fast?.22:.5],[100,0]),0,.91,-1,0]}/><div style={{position:'absolute',left:65,top:760,transform:`translateX(${(1-ent)*-300}px) rotate(-8deg)`}}><Mascot size={230} color={accent} state="thinking"/></div></>}
 {feature&&<><div style={{position:'absolute',top:1200,bottom:0,left:0,right:0,background:'#070b14'}}/><Caption s={s} t={t}/>{s.kind==='dual'&&<><div style={{position:'absolute',top:1230,left:0,right:0,display:'flex',justifyContent:'space-around',fontSize:25,color:accent}}><span>My Progress</span><span>Attendance</span></div><div style={{position:'absolute',bottom:170,width:'100%',textAlign:'center',fontSize:18,color:'#8290a6'}}>Illustrative attendance data</div></>}</>}
 {s.kind==='universities'&&<div style={{position:'absolute',top:1480,left:70,right:70,textAlign:'center',fontSize:22,lineHeight:1.35,color:'#bdcadc'}}>Tamil Nadu Dr. M.G.R. Medical University<br/>Kerala University of Health Sciences</div>}
 {s.kind==='india'&&<><div style={{position:'absolute',top:240,width:'100%',textAlign:'center',fontSize:28,letterSpacing:6,color:'#aebbcf'}}>FROM A STUDENT’S DESK</div><div style={{position:'absolute',top:490,left:305,transform:`translateY(${(1-ent)*90}px) rotate(${v(t,[0,.8,s.d],[8,-3,1])}deg)`}}><Mascot size={470} state="wide"/></div><div style={{position:'absolute',top:1110,width:'100%',textAlign:'center',fontSize:85,fontWeight:800,letterSpacing:-3}}><Words text={s.caption} t={t}/></div><div style={{position:'absolute',top:1240,width:'100%',textAlign:'center',fontSize:36,color:'#bdc6d9'}}>{s.sub}</div><div style={{position:'absolute',top:1400,left:260,width:560,display:'flex',gap:12}}>{['#ff9f5a','#f4f7ff','#79cba3'].map((c,i)=><div key={c} style={{height:6,flex:1,background:c,borderRadius:4,transform:`scaleX(${v(t,[.3+i*.1,.85+i*.1],[.6,1])})`,opacity:v(t,[.3+i*.1,.7+i*.1],[0,1])}}/>)}</div></>}
 {s.kind==='numbers'&&<><div style={{position:'absolute',top:185,width:'100%',textAlign:'center',fontSize:28,letterSpacing:4,color:'#3b606b'}}>UNIVERSITY MBBS COLLEGE LISTS</div><div style={{position:'absolute',top:340,width:'100%',display:'flex',justifyContent:'center',gap:100,transform:`translateY(${(1-ent)*80}px)`}}>{[[60,'TNMGR'],[35,'KUHS']].map(([n,label],i)=><div key={label} style={{textAlign:'center'}}><div style={{fontSize:245,lineHeight:1,fontWeight:850,letterSpacing:-10,color:i?'#6f4ca5':'#147971'}}>{Math.max(1,Math.round(v(t,[.15,.65],[1,n as number])))}</div><div style={{fontSize:24,letterSpacing:2,marginTop:30}}>{label}</div></div>)}</div>{['tnmgr-first','kuhs-second','tnmgr-third','kuhs-subjects'].map((file,i)=><Phone key={file} file={file} pose={[(i-1.5)*230,245,.35,(i-1.5)*7,0]}/>)}<div style={{position:'absolute',top:1450,width:'100%',textAlign:'center',fontSize:52,fontWeight:800,lineHeight:1.12}}><Words text={s.caption} t={t}/></div><div style={{position:'absolute',top:1270,width:'100%',textAlign:'center',fontSize:27,color:'#43626d'}}>Listed MBBS colleges • Not ORBIT users</div><div style={{position:'absolute',top:1325,left:60,right:60,textAlign:'center',fontSize:20,color:'#43626d'}}>Sources: TNMGR 2026–27 list · KEAM 2026 prospectus</div></>}
 {s.kind==='end'&&<><div style={{position:'absolute',top:145,width:'100%',textAlign:'center'}}><Img src={staticFile('orbit-logo.png')} style={{width:220,height:305,objectFit:'contain'}}/></div><div style={{position:'absolute',top:music?560:595,left:60,right:60,textAlign:'center',fontSize:music?92:102,fontWeight:850,letterSpacing:-4}}><Words text={s.caption} t={t} big/></div><div style={{position:'absolute',top:795,width:'100%',textAlign:'center',fontSize:32,color:accent}}>TNMGR · KUHS</div><div style={{position:'absolute',top:930,left:190,transform:`rotate(-6deg) translateY(${(1-ent)*50}px)`}}><Mascot size={230} state="wink"/></div><div style={{position:'absolute',top:1020,left:400,opacity:v(t,[.45,.9],[0,1])}}><Play/></div><div style={{position:'absolute',top:1390,width:'100%',textAlign:'center',fontSize:31,fontWeight:700,letterSpacing:3}}>ORBIT MBBS</div><div style={{position:'absolute',top:1490,width:'100%',textAlign:'center',fontSize:24,color:'#a2b2ca'}}>Made in India. Built for your next chapter.</div></>}
 <div style={{position:'absolute',left:60,top:55,fontSize:20,letterSpacing:4,color:isLight?'#345766':'#8291aa'}}>ORBIT MBBS</div>
 <div style={{position:'absolute',right:60,top:55,fontSize:20,letterSpacing:2,color:isLight?'#147971':accent}}>TNMGR + KUHS</div>
 </AbsoluteFill>}
export const CommonPromo=({music=false}:{music?:boolean})=>{return <AbsoluteFill style={{background:'#070b14',fontFamily:'OrbitRoboto,Arial,sans-serif'}}><Audio src={staticFile(music?'audio/music-mix.wav':'audio/voice-only.wav')} volume={1}/>{(music?musicShots:shots).map((s,i)=><Sequence key={i} from={Math.round(s.at*60)} durationInFrames={Math.round(s.d*60)} premountFor={60}><Scene s={s} index={i} music={music}/></Sequence>)}</AbsoluteFill>};

export const FastPromo=()=> <AbsoluteFill style={{background:"#070b14",fontFamily:"OrbitRoboto,Arial,sans-serif"}}><Audio src={staticFile("audio/fast-music-only.wav")}/>{fastShots.map((s,i)=><Sequence key={i} from={Math.round(s.at*60)} durationInFrames={Math.round(s.d*60)}><Scene s={s} index={i} music fast/></Sequence>)}</AbsoluteFill>;

export const BeatPromo=({silent=false}:{silent?:boolean})=> <AbsoluteFill style={{background:"#070b14",fontFamily:"OrbitRoboto,Arial,sans-serif"}}>{!silent&&<Audio src={staticFile("audio/beat-music-only.wav")}/>} {beatShots.map((s,i)=><Sequence key={i} from={Math.round(s.at*60)} durationInFrames={Math.round(s.d*60)}><Scene s={s} index={i} music/></Sequence>)}</AbsoluteFill>;
